name: smartflore
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  flutter_map: 
    git:
      url: https://github.com/fleaflet/flutter_map.git
  flutter_bloc: ^8.0.1
  sliding_up_panel: ^2.0.0+1
  flutter_svg: ^1.0.3
  flutter_image: ^4.1.0
  latlong2: ^0.8.1
  shared_preferences: ^2.0.13
  equatable: ^2.0.3
  http: ^0.13.4
  json_annotation: ^4.4.0
  package_info_plus: ^1.4.2
  geolocator: ^9.0.1
  cached_network_image: ^3.2.0
  pretty_logger: any
  flutter_native_splash: ^2.1.6
  carousel_slider: ^4.1.1
  webview_flutter: ^3.0.4
  collection: ^1.16.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.1.10
  freezed: ^2.0.2
  freezed_annotation: ^2.0.1
  json_serializable: ^6.1.6
  icons_launcher: ^1.1.7

flutter_icons:
  ios: true
  android: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: 'assets/icons/icon_bg.png'
  adaptive_icon_foreground: 'assets/icons/icon_fg.png'
  adaptive_icon_round: 'assets/icons/icon_round.png'

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/graphics/
 
  fonts:
    - family: SmartFloreIcons
      fonts:
        - asset: assets/fonts/SmartFloreIcons.ttf
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.ttf
        - asset: assets/fonts/SourceSansPro-SemiBold.ttf
          weight: 600

flutter_native_splash:
  #color: "#FF7469"
  background_image: "assets/splashscreen/splash_bg.png"
  image: assets/splashscreen/splash_icon.png

  #color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png
  #branding_dark: assets/dart_dark.png

  # Android 12 handles the splash screen differently than previous versions.  Please visit
  # https://developer.android.com/guide/topics/ui/splash-screen
  # Following are Android 12 specific parameter.
  android_12:
    # The image parameter sets the splash screen icon image.  If this parameter is not specified,
    # the app's launcher icon will be used instead.
    # Please note that the splash screen will be clipped to a circle on the center of the screen.
    # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
    # 640 pixels in diameter.
    # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
    # 768 pixels in diameter.
    image: assets/splashscreen/splash_icon_android12.png
    icon_background_color: "#FF7469"
    #image_dark: assets/android12splash-invert.png
    #icon_background_color_dark: "#eeeeee"
  fullscreen: true
