name: smartflore
description: Smart’Flore invite à revisiter ces coins de nature parfois oubliés
  de notre environnement proche et devient prétexte à sortir et créées du lien
  avec cette nature.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+45

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  algolia: ^1.1.2
  another_flushbar: ^1.12.29
  app_settings: ^4.1.8
  auto_size_text: ^3.0.0
  bloc: ^8.0.3
  cached_network_image: ^3.2.0
  camera: ^0.10.0+4
  carousel_slider: ^4.1.1
  collection: ^1.16.0
  connectivity_plus: ^3.0.3
  cupertino_icons: ^1.0.2
  envied: ^0.3.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_animate: ^4.0.0
  flutter_bloc: ^8.0.1
  flutter_cache_manager: ^3.3.0
  flutter_html: ^3.0.0-alpha.5
  flutter_image: ^4.1.0
  flutter_localizations:
    sdk: flutter
  flutter_map: ^3.1.0
  flutter_native_splash: ^2.1.6
  flutter_svg: ^1.0.3
  freezed_annotation: ^2.1.0
  geolocator: ^9.0.1
  group_button: ^5.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html: ^0.15.0
  http: ^0.13.4
  image_fade: ^0.6.1
  infinite_scroll_pagination: ^3.2.0
  intl: ^0.17.0
  json_annotation: ^4.8.0
  latlong2: ^0.8.1
  package_info_plus: ^3.0.3
  path: ^1.8.2
  path_provider: ^2.0.11
  photo_view: ^0.14.0
  pretty_logger: any
  sliding_up_panel: ^2.0.0+1
  url_launcher: ^6.1.9
  webview_flutter: ^4.0.1

dev_dependencies:
  build_runner: ^2.3.3
  envied_generator: ^0.3.0

  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.0.2
  hive_generator: ^2.0.0
  icons_launcher: ^2.1.0
  json_serializable: ^6.1.6

flutter_icons:
  ios: true
  android: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "assets/icons/icon_bg.png"
  adaptive_icon_foreground: "assets/icons/icon_fg.png"
  adaptive_icon_round: "assets/icons/icon_round.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/graphics/

  fonts:
    - family: SmartFloreIcons
      fonts:
        - asset: assets/fonts/SmartFloreIcons.ttf
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.ttf
        - asset: assets/fonts/SourceSansPro-SemiBold.ttf
          weight: 600

flutter_native_splash:
  #color: "#FF7469"
  background_image: "assets/splashscreen/splash_bg.png"
  image: assets/splashscreen/splash_icon.png

  #color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png
  #branding_dark: assets/dart_dark.png
  # Android 12 handles the splash screen differently than previous versions.  Please visit
  # https://developer.android.com/guide/topics/ui/splash-screen
  # Following are Android 12 specific parameter.
  android_12:
    # The image parameter sets the splash screen icon image.  If this parameter is not specified,
    # the app's launcher icon will be used instead.
    # Please note that the splash screen will be clipped to a circle on the center of the screen.
    # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
    # 640 pixels in diameter.
    # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
    # 768 pixels in diameter.
    image: assets/splashscreen/splash_icon_android12.png
    icon_background_color: "#FF7469"
    #image_dark: assets/android12splash-invert.png
    #icon_background_color_dark: "#eeeeee"
  fullscreen: true
