/// Flutter icons SmartFloreIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SmartFloreIcons
///      fonts:
///       - asset: fonts/SmartFloreIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class SmartFloreIcons {
  SmartFloreIcons._();

  static const _kFontFam = 'SmartFloreIcons';
  static const String? _kFontPkg = null;

  static const IconData qrcode =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData path =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pin =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plant =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData setting =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData target =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrowRight =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
